### PR TITLE
API first steps

### PR DESCRIPTION
**Pull request by CsengerG**
See `README` and `#general` to see what this does.

### CODE REVIEW

**Comment by pmernyei** [comment]
Looks great, I'll set up and test later tonight

**Comment by pmernyei** [comment]
3 things I'm not sure about:

1. Not sure what the `source env/bin/activate` command was supposed to do, but I didn't even have a `bin` folder in `env` so it couldn't run. Seemed to work fine without that step though?
2. Tried to poke the server from curl after starting it, got a HTTP 400 error and this output from the server's terminal:
```
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /api/people/
[10/Feb/2019 23:41:22] "GET /api/people/ HTTP/1.1" 400 61903
```
3. Seems a bit confusing to have the toplevel front_end folder and a frontend folder in the django folder as well. Also to have the django folder be `FeverFinder/fever_finder`. :D Not really sure what how it should end up looking / what the workflow is going to be to have django actually serve the frontend though. Also note that we'll have an app in the repo as well!

**Comment by gezacsenger** [comment]
Addressing some of the points from @MPeti01 :
1. `virtualenv` sets up a virtual environment where you can install Python packages as you want to. That's convenient when you are developing multiple Python projects because of dependencies, different versioning, etc. What `source env/bin/activate` does is basically just entering this virtual environment. I think what happened in your case was that you installed the Python packages globally (and yes, that should work too). That's fine, it shouldn't matter, as long as you don't have other Python projects using the same libraries.

2. Last commit should fix this.
3. You are welcome to rename the `front_end` folder at the root, it shouldn't matter much what it's called. That's not true for the Django project though. I think it would be best to leave the project called as `fever_finder` and have a Django app called `frontend` in the Django project folder, because that seems to be the convention (also, I don't really feel comfortable with renaming apps without having _very_ good reasons to do so).

> Also note that we'll have an app in the repo as well!

Yes, that shouldn't matter much from the build point of view. Front end + back end at the web app site is much stronger coupled. If we'll have something for the app, we can just put that into a third folder in the root.

**Comment by mdaudali** [comment]
I've had a look at it over last night and right now - everything looks good. As you said, limited amount of custom code and the infrastructure works. I'm approving.

**Review by mdaudali — APPROVED** [review]

**Pull request merged**
